apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-demo
  namespace: rollback-demo

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%

  selector:
    matchLabels:
      app: rollback-demo

  template:
    metadata:
      labels:
        app: rollback-demo

    spec:
      containers:
        - name: nginx
          image: pes2ug19cs219/harness-rollback:<+artifact.tag>
          command:
            - /bin/does-not-exist
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
